<p><a href="/test/util-get-end-date">Util::get_end_date()</a></p>
<p><a href="/test/util-get-end-date-reverse">Util::get_end_date() reverse</a></p>
<p>--------------------------------------------------------------------</p>
<p><a href="/test/util-get-work-end-date-weekend">Util::get_work_end_date() weekend</a></p>
<p><a href="/test/util-get-work-end-date-weekend-reverse">Util::get_work_end_date() weekend reverse</a></p>

<p><a href="/test/util-get-work-end-date-saturday">Util::get_work_end_date() saturday</a></p>
<p><a href="/test/util-get-work-end-date-saturday-reverse">Util::get_work_end_date() saturday reverse</a></p>

<p><a href="/test/util-get-work-end-date-sunday">Util::get_work_end_date() sunday</a></p>
<p><a href="/test/util-get-work-end-date-sunday-reverse">Util::get_work_end_date() sunday reverse</a></p>
<p>--------------------------------------------------------------------</p>
<p><a href="/test/util-count-days">Util::count_days()</a></p>
<p><a href="/test/util-count-days-reverse">Util::count_days() reverse</a></p>
<p>--------------------------------------------------------------------</p>
<p><a href="/test/util-count-work-days-date-weekend">Util::count_work_days() date weekend</a></p>
<p><a href="/test/util-count-work-days-date-weekend-reverse">Util::count_work_days() date weekend reverse</a></p>
<p><a href="/test/util-count-work-days-days-weekend">Util::count_work_days() days weekend</a></p>
<p><a href="/test/util-count-work-days-days-weekend-reverse">Util::count_work_days() days weekend reverse</a></p>

<p><a href="/test/util-count-work-days-date-saturday">Util::count_work_days() date saturday</a></p>
<p><a href="/test/util-count-work-days-date-saturday-reverse">Util::count_work_days() date saturday reverse</a></p>
<p><a href="/test/util-count-work-days-days-saturday">Util::count_work_days() days saturday</a></p>
<p><a href="/test/util-count-work-days-days-saturday-reverse">Util::count_work_days() days saturday reverse</a></p>

<p><a href="/test/util-count-work-days-date-sunday">Util::count_work_days() date sunday</a></p>
<p><a href="/test/util-count-work-days-date-sunday-reverse">Util::count_work_days() date sunday reverse</a></p>
<p><a href="/test/util-count-work-days-days-sunday">Util::count_work_days() days sunday</a></p>
<p><a href="/test/util-count-work-days-days-sunday-reverse">Util::count_work_days() days sunday reverse</a></p>
<p>--------------------------------------------------------------------</p>
<p><a href="/test/util-count-free-days-date-weekend">Util::count_free_days() date weekend</a></p>
<p><a href="/test/util-count-free-days-date-weekend-reverse">Util::count_free_days() date weekend reverse</a></p>
<p><a href="/test/util-count-free-days-days-weekend">Util::count_free_days() days weekend</a></p>
<p><a href="/test/util-count-free-days-days-weekend-reverse">Util::count_free_days() days weekend reverse</a></p>

<p><a href="/test/util-count-free-days-date-saturday">Util::count_free_days() date saturday</a></p>
<p><a href="/test/util-count-free-days-date-saturday-reverse">Util::count_free_days() date saturday reverse</a></p>
<p><a href="/test/util-count-free-days-days-saturday">Util::count_free_days() days saturday</a></p>
<p><a href="/test/util-count-free-days-days-saturday-reverse">Util::count_free_days() days saturday reverse</a></p>

<p><a href="/test/util-count-free-days-date-sunday">Util::count_free_days() date sunday</a></p>
<p><a href="/test/util-count-free-days-date-sunday-reverse">Util::count_free_days() date sunday reverse</a></p>
<p><a href="/test/util-count-free-days-days-sunday">Util::count_free_days() days sunday</a></p>
<p><a href="/test/util-count-free-days-days-sunday-reverse">Util::count_free_days() days sunday reverse</a></p>
<p>--------------------------------------------------------------------</p>
<p><a href="/test/util-count-week-days-date">Util::count_week_days() date</a></p>
<p><a href="/test/util-count-week-days-date-reverse">Util::count_week_days() date reverse</a></p>
<p><a href="/test/util-count-week-days-days">Util::count_week_days() days</a></p>
<p><a href="/test/util-count-week-days-days-reverse">Util::count_week_days() days reverse</a></p>